version: '{build}'
clone_folder: C:\gopath\src\github.com\govenue\fsintra
environment:
  GOPATH: C:\gopath
build_script:
- cmd: >-
    go version

    go env

    go get -v github.com/govenue/fsintra/...

    go build github.com/govenue/fsintra
test_script:
- cmd: go test -race -v github.com/govenue/fsintra/...
